services:
  db:
    build: ./db
    container_name: postgres
    restart: always
    networks:
      - lafc-network
    environment:
      POSTGRES_DB: lafc_dev
      POSTGRES_USER: lafc_user
      POSTGRES_PASSWORD: thisis3252ahoo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  flask:
    build: ./app
    container_name: flask
    restart: always
    networks:
      - lafc-network
    depends_on:
      - db
    environment:
      POSTGRES_DB: lafc_dev
      POSTGRES_USER: lafc_user
      POSTGRES_PASSWORD: thisis3252ahoo
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      JUPYTER_PORT: 8888
    ports:
      - "4444:4444"
    volumes:
      - ./app:/app 
  jupyter:
    build: ./jupyter
    container_name: jupyter
    restart: always
    networks:
      - lafc-network
    depends_on:
      - db
      - flask
    environment:
      POSTGRES_DB: lafc_dev
      POSTGRES_USER: lafc_user
      POSTGRES_PASSWORD: thisis3252ahoo
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/notebooks:/home/jovyan/work
      - ./jupyter/jupyter_notebook_config.py:/home/jovyan/.jupyter/jupyter_notebook_config.py
volumes:
  postgres_data:
networks:
  lafc-network:
